### ISSUE TITLE
Phantom.js error when installing(Cannot install because of this)

### ISSUE THREAD

**Issue by Oleander2911** [Alex-Rose/fb-messenger-cli#109] opened 2017-08-27 20:17 UTC
Hey, nice tool, whish i could try it, but i keep getting an error when installing:

```
> phantomjs-prebuilt@2.1.15 install /usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1503864908769/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1503864908769/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1503864908769/phantomjs-2.1.1-macosx',
  dest: '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1503864908769/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christoffernielsen/.npm/_logs/2017-08-27T20_15_11_635Z-debug.log
```

**Comment by xZero707** [comment] 2017-08-31 13:20
You need to use sudo before node/npm command.

**Comment by Oleander2911** [comment] 2017-08-31 19:00
I did that several times, still the same error:
```
[christoffernielsen:~]$ sudo npm install -g fb-messenger-cli
Password:
/usr/local/bin/fb-messenger-cli -> /usr/local/lib/node_modules/fb-messenger-cli/cli.js

> phantomjs-prebuilt@2.1.15 install /usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1504205991712/phantomjs-2.1.1-macosx -> /usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1504205991712/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1504205991712/phantomjs-2.1.1-macosx',
  dest: '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1504205991712/phantomjs-2.1.1-macosx' -> '/usr/local/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/christoffernielsen/.npm/_logs/2017-08-31T18_59_54_805Z-debug.log
```

**Comment by SamBergeron** [comment] 2017-08-31 20:10
Yeah this looks more like npm is trying to install phantomJS over (what looks like) an other installation. 
Can you try just running "npm install phantomjs-prebuilt" and posting the log here?

**Comment by remembertoremind** [comment] 2017-09-19 12:09
I believe I have a similar problem, and I have tried the suggested solution. However, I'm very much a noob so please be gentle :)
4.12.13-1-ARCH #1 SMP PREEMPT Fri Sep 15 06:36:43 UTC 2017 x86_64 GNU/Linux

`chansen@frederik ~ % sudo npm install phantomjs-prebuilt 
[sudo] password for chansen: 

> phantomjs-prebuilt@2.1.15 install /home/chansen/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /home/chansen/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1505822547035/phantomjs-2.1.1-linux-x86_64 -> /home/chansen/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /home/chansen/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm WARN saveError ENOENT: no such file or directory, open '/home/chansen/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/chansen/package.json'
npm WARN chansen No description
npm WARN chansen No repository field.
npm WARN chansen No README data
npm WARN chansen No license field.

+ phantomjs-prebuilt@2.1.15
added 87 packages in 6.617s`

`chansen@frederik ~ % sudo npm install -g install fb-messenger-cli
/usr/bin/fb-messenger-cli -> /usr/lib/node_modules/fb-messenger-cli/cli.js

> phantomjs-prebuilt@2.1.15 install /usr/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Verified checksum of previously downloaded file
Extracting tar contents (via spawned process)
Removing /usr/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1505822578537/phantomjs-2.1.1-linux-x86_64 -> /usr/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom
chmod failed: phantomjs was not successfully copied to /usr/lib/node_modules/fb-messenger-cli/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs-prebuilt@2.1.15 install: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phantomjs-prebuilt@2.1.15 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-09-19T12_03_03_305Z-debug.log`

I have looked at the log, but it does not give me any further information:

`3858 verbose argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "install" "fb-messen
ger-cli"
3859 verbose node v8.5.0
3860 verbose npm  v5.3.0
3861 error code ELIFECYCLE
3862 error errno 1
3863 error phantomjs-prebuilt@2.1.15 install: `node install.js`
3863 error Exit status 1
3864 error Failed at the phantomjs-prebuilt@2.1.15 install script.
3864 error This is probably not a problem with npm. There is likely additional loggi
ng output above.
3865 verbose exit [ 1, true ]`

Any help your be awesome :) Thanks.

**Comment by romainrichard** [comment] 2017-09-29 06:59
This looks like a duplicate of #94. I just posted a solution that worked for me: https://github.com/Alex-Rose/fb-messenger-cli/issues/94#issuecomment-333047050

**Comment by sajattack** [comment] 2017-10-03 18:21
It works if you add --ignore-scripts

**Comment by SamBergeron** [comment] 2017-10-04 19:38
Indeed this is the same as #94, so I'll close this as it's a duplicate.
There is a statement there, I'm trying to resolve a lot of issues linked to phantomJS, simply by changing my headless client.

**Closed by SamBergeron** 2017-10-04 19:38 UTC
