### ISSUE TITLE
Login Issues, JSON Parse error: Unexpected EOF

### ISSUE THREAD

**Issue by kenzietandun** [Alex-Rose/fb-messenger-cli#35] opened 2017-03-19 23:23 UTC
```
Can't find the .kryptonite file, we'll make a new one
Facebook credentials
prompt: email:  (mail@mail.com)
prompt: password:  
undefined:1
SyntaxError: JSON Parse error: Unexpected EOF
^

SyntaxError: Unexpected token S in JSON at position 0
    at Object.parse (native)
    at Socket.<anonymous> (/usr/local/lib/node_modules/fb-messenger-cli/scripts/login.js:36:28)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```

Running openSUSE Tumbleweed, installed fb-messenger-cli with npm6.
I used the same login on the browser and it works fine. No special chars in my password or email.
I thought it was my ad-blocking DNS server that's causing issues, tried connecting via VPN from my VPS but didn't work still.

**Comment by SamBergeron** [comment] 2017-03-24 16:03
Give it a try now, and let me know. I fixed a race condition we had (bad callback placement). I may have been what was affecting you because you were behind a vpn and the requests were coming out of sync. 
I can't guarantee anything, because I couldn't reproduce. But worth a shot. 

Should be fixed in 0b0c89db609e9d2701e950083f3d90383316a00a

**Comment by landonxjames** [comment] 2017-03-28 18:10
```
Can't find the .kryptonite file, we'll make a new one
Facebook credentials
Email: mail@mail.com
Password: password
Warning : settings not found, lets try to create default
Launching app...
fb-messenger-cli\scripts\messnger.js:36
  if (body.indexOf('for (;;);') === 0) {
          ^

TypeError: Cannot read property 'indexOf' of undefined
    at Messenger.cleanJson (fb-messenger-cli\scripts\messenger.js:36:11)
    at Request._callback (fb-messenger-cli\scripts\messenger.js:438:22)
    at self.callback (fb-messnger-cli\node_modules\request\request.js:188:22)
    at emitOne (events.js:82:20)
    at Request.emit (events.js:169:7)
    at Request.onRequestError (fb-messenger-cli\node_modules\request\request.js:884:8)
    at emitOne (events.js:77:13)
    at ClientRequest.emit (events.js:169:7)
    at TLSSocket.socketErrorListener (_http_client.js:256:9)
    at emitOne (events.js:77:13)
```

I believe I am having a similar/related issue. I get the above error message each time I try to login.

**Comment by SamBergeron** [comment] 2017-05-11 17:37
Merging this into common issue (#53)

**Closed by SamBergeron** 2017-05-11 17:37 UTC
