### ISSUE TITLE
"Unexpected end of JSON input" when selecting a conversation

### ISSUE THREAD

**Issue by phito** [Alex-Rose/fb-messenger-cli#123] opened 2017-12-03 22:41 UTC
Launched the program, logged in, and this happens when I try to select a conversation

```
> 2
undefined:1
SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request._callback (/usr/lib/node_modules/fb-messenger-cli/scripts/messenger.js:244:25)
    at Request.self.callback (/usr/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:186:22)
    at emitTwo (events.js:125:13)
    at Request.emit (events.js:213:7)
    at Request.<anonymous> (/usr/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1163:10)
    at emitOne (events.js:115:13)
    at Request.emit (events.js:210:7)
    at Gunzip.<anonymous> (/usr/lib/node_modules/fb-messenger-cli/node_modules/request/request.js:1085:12)
    at Object.onceWrapper (events.js:312:30)
```

**Comment by simisimis** [comment] 2017-12-04 15:06
Having same issue. This morning it just stopped working

**Comment by Alex-Rose** [comment] 2017-12-04 20:16
Fixed. Duplicate of #124

**Closed by Alex-Rose** 2017-12-04 20:16 UTC
