### ISSUE TITLE
Error while searching for contact: Could not find thread information for thread 

### ISSUE THREAD

**Issue by janfitz** [Alex-Rose/fb-messenger-cli#152] opened 2018-02-19 09:26 UTC
When I try to find a conversation (contact) using `/ search ', I get the following error. The error is displayed after inputing number of selected conversation.  I tested it on several conversations.

```
Error: Could not find thread information for thread with 100002196806842
    at Listeners.getThreadInfo (/home/janfitz/.bot/scripts/listeners.js:26:25)
    at InteractiveCli.initializeConversationViewFromFbid (/home/janfitz/.bot/scripts/interactive.js:189:15)
    at emitter.emit (/home/janfitz/.bot/scripts/interactive.js:487:33)
    at Listeners.searchListener (/home/janfitz/.bot/scripts/listeners.js:111:17)
    at emitTwo (events.js:126:13)
    at EventEmitter.emit (events.js:214:7)
    at Interface.InteractiveCli.handler (/home/janfitz/.bot/scripts/interactive.js:484:21)
    at emitOne (events.js:116:13)
    at Interface.emit (events.js:211:7)
    at Interface._onLine (readline.js:282:10)
Exiting...
```

**Comment by SamBergeron** [comment] 2018-02-28 17:57
Actually yeah this is a duplicate of #145.
Same error, same line numbers. :)

**Closed by SamBergeron** 2018-02-28 17:57 UTC

**Comment by janfitz** [comment] 2018-03-02 12:46
Sorry for misunderstanding. I was using incorrect branche (chromium). :)
